[build]
  publish = "dist"
  command = "npm run build:production"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"

# Production context
[context.production]
  command = "npm run build:production"

# Deploy preview context
[context.deploy-preview]
  command = "npm run build:staging"

# Branch deploy context
[context.branch-deploy]
  command = "npm run build:staging"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=()"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Don't cache HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment-specific settings
[context.production.environment]
  VITE_APP_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_APP_ENVIRONMENT = "staging"

[context.branch-deploy.environment]
  VITE_APP_ENVIRONMENT = "staging"